In [1]:
import numpy as np
import gym
import random

In [3]:
env = gym.make("FrozenLake-v1")

In [4]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [5]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
total_episodes = 15000        
learning_rate = 0.8           
max_steps = 99                
gamma = 0.95                  


epsilon = 1.0                 
max_epsilon = 1.0             
min_epsilon = 0.01            
decay_rate = 0.005             

In [10]:

import numpy as np
import random



rewards = []


for episode in range(total_episodes):
    
    state_tuple = env.reset()
    state = state_tuple[0]  
    done = False
    total_rewards = 0

    for step in range(max_steps):
        
        exp_exp_tradeoff = random.uniform(0, 1)

        
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[int(state), :])  

        
        else:
            action = env.action_space.sample()

        
        new_state, reward, done, info = env.step(action)[:4]
        qtable[int(state), action] = qtable[int(state), action] + learning_rate * (
                    reward + gamma * np.max(qtable[int(new_state), :]) - qtable[int(state), action])  

        total_rewards += reward

        
        state = new_state

        
        if done:
            break

    
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)

print("Score over time: " + str(sum(rewards) / total_episodes))
print(qtable)


Score over time: 0.48146666666666665
[[2.56693173e-01 3.64871898e-02 4.17620047e-02 3.26594696e-02]
 [1.01068708e-02 6.26943218e-03 9.56578157e-03 2.13543361e-01]
 [1.23906952e-02 2.11392968e-02 8.87886384e-03 2.49511563e-01]
 [5.06840235e-04 8.18797908e-03 2.82662744e-03 2.30715007e-02]
 [2.60507622e-01 3.40336414e-02 1.80621037e-03 8.38075760e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.94754795e-02 4.77122184e-04 4.43727018e-06 2.16941993e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.22531065e-02 2.05037970e-03 3.70816504e-02 1.10469739e-01]
 [6.79261404e-04 5.65525536e-01 2.85360619e-02 1.43180356e-03]
 [8.96642422e-01 3.23755312e-04 5.03168136e-03 7.87004896e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.07153846e-01 5.26500869e-03 6.38717942e-01 7.29071925e-03]
 [2.87112074e-01 9.97814977e-01 3.04671700e-01 2.18494142e-01]
 [0.00000000e+00 0

In [26]:
env.reset()

for episode in range(100):
    state = env.reset()[:1]
    print(state)
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        
        action = np.argmax(qtable[state,:])
        
        
        new_state, reward, done, info = env.step(action)[:4]
        c = 0
        if done:
            
            env.render()
            c=  c+1   
            print("Number of steps", step)
            break
        state = new_state
env.close()
print(c)

(0,)
****************************************************
EPISODE  0
Number of steps 32
(0,)
****************************************************
EPISODE  1
Number of steps 97
(0,)
****************************************************
EPISODE  2
Number of steps 7
(0,)
****************************************************
EPISODE  3
Number of steps 28
(0,)
****************************************************
EPISODE  4
Number of steps 82
(0,)
****************************************************
EPISODE  5
Number of steps 40
(0,)
****************************************************
EPISODE  6
Number of steps 63
(0,)
****************************************************
EPISODE  7
Number of steps 92
(0,)
****************************************************
EPISODE  8
Number of steps 10
(0,)
****************************************************
EPISODE  9
Number of steps 13
(0,)
****************************************************
EPISODE  10
Number of steps 29
(0,)
***************************

c:\Users\sutar\AppData\Local\Programs\Python\Python311\Lib\site-packages\gym\envs\toy_text\frozen_lake.py:271: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("FrozenLake-v1", render_mode="rgb_array")
  logger.warn(


Number of steps 16
(0,)
****************************************************
EPISODE  88
Number of steps 30
(0,)
****************************************************
EPISODE  89
Number of steps 68
(0,)
****************************************************
EPISODE  90
Number of steps 63
(0,)
****************************************************
EPISODE  91
Number of steps 82
(0,)
****************************************************
EPISODE  92
Number of steps 18
(0,)
****************************************************
EPISODE  93
Number of steps 26
(0,)
****************************************************
EPISODE  94
Number of steps 15
(0,)
****************************************************
EPISODE  95
Number of steps 26
(0,)
****************************************************
EPISODE  96
Number of steps 38
(0,)
****************************************************
EPISODE  97
Number of steps 11
(0,)
****************************************************
EPISODE  98
Number of steps 70
(0